name: 'Setup Git w/daylin-bot'
description: 'use git as daylin-bot'

runs:
  using: "composite"
  steps:
    - name: Setup Bot
      shell: bash
      run: |
        git --version
        git config user.name 'daylin-bot'
        git config user.email 'bot@dayl.in'
